### ISSUE TITLE
Qulqu'un intéréssé par https://about.gitlab.com/

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/cyclec2018#15]
GitLab

**Comment by abedelazizbilani** [comment]
mon sujet initial est le web semantique, je peux faire ca aussi

**Comment by abedelazizbilani** [comment]
https://github.com/abedelazizbilani/C1-2017-2018/blob/master/README.md
  a la place de https://github.com/abedelazizbilani/C1-2018

**Comment by pascalfares** [comment]
Ok changé
