### ISSUE TITLE
chapitre a présenter après les vacances

### ISSUE THREAD

**Issue by abedelazizbilani** [ISSAE/cyclec2018#2]

**Comment by pascalfares** [comment]
As tu choisi un sujet?

**Comment by josephmansour** [comment]
J'ai choisi le sujet Cassandra

Joseph Mansour

**Comment by pascalfares** [comment]
Voir instruction #3

**Comment by ralphsa95** [comment]
Est-ce que les projets a choisir sont mis sur un lien online pour choisir un d'eux?
