### ISSUE TITLE
Pour choisir son sujet

### ISSUE THREAD

**Issue by pascalfares** [ISSAE/cyclec2018#3]
Créer votre projet dans github, remplir le README.md de votre projet avec présentation rapide du travail que vous vous proposer de présenté. Faire reply ici avec le lien de votre projet....

- [ ] Créer votre projet github
- [ ] Décrire votre proposition dans README.md
- [ ] faire reply ici avec le liens

**Comment by fadyzakharia** [comment]
Bonjour Dr Fares,
mon sujet : Firebase Realtime Database
Lien : 
https://github.com/fadyzakharia/projetC1/blob/master/README.md

Joyeux Noel et Bonne année

**Comment by Youssef-Kassouf** [comment]
Mon sujet: Firebase Cloud Firestore
https://github.com/Youssef-Kassouf/CNAM-ProjetC1-2018.git

**Comment by HazemHalawi** [comment]
Bonjour Dr,
Proposition du sujet: MongoDB
Lien: https://github.com/HazemHalawi/cyclec-2018/blob/master/README.md

**Comment by abedelazizbilani** [comment]
Sujet : Web Semantique
Lien : https://github.com/abedelazizbilani/C1-2018/blob/master/README.md

**Comment by faheddany** [comment]
Sujet: Neo4j
Lien: https://github.com/faheddany/neo4j-cyclec/blob/master/README.md

**Comment by RodneyBadran** [comment]
Cher Dr. Pascal,
Je choisis le sujet "MongoDB"
https://github.com/RodneyBadran/sujet-3/blob/master/README.md

Joyeux Noel et Bonne Annee.

**Comment by romyephrem** [comment]
Mon sujet est JUNIT 
https://github.com/romyephrem/C1projet2018

**Comment by eliekh1** [comment]
Sujet : CouchDB
https://github.com/eliekh1/Project-C1-2018/blob/master/README.md

**Comment by said-eid** [comment]
Sujet : Riak DB
https://github.com/said-eid/ProjetC1-2018/blob/master/README.md

**Comment by rkhawand** [comment]
Sujet : Google Cloud Platform - App Engine
https://github.com/rkhawand/Projet-SMB214-2018

**Comment by DianaDaher** [comment]
Sujet: Grizzly
https://github.com/DianaDaher/PROJETC1-2018

**Comment by ralphsa95** [comment]
Sujet: Rapport SQL Jasper
https://github.com/ralphsa95/ProjetC12018/blob/master/README.md

**Comment by roudy-ghosn** [comment]
Sujet: Tomcat Server
https://github.com/roudy-ghosn/ProjetC1/blob/master/README.md

**Comment by EphremBeainoCNAM** [comment]
Azure Table Storage:
https://github.com/EphremBeainoCNAM/ProjetC1-2018

**Comment by ayman-kouzayha** [comment]
Sujet: Google Cloud Compute Engine
https://github.com/ayman-kouzayha/Google_Cloud_Compute_Engine/blob/master/README.md

**Comment by JoelleTannous** [comment]
Sujet: tomEE server
https://github.com/JoelleTannous/projet-C1-2018

**Comment by dchouba** [comment]
Sujet: OAuth2
https://github.com/dchouba/oauth2-Cyclec/blob/master/README.md

**Comment by pascalfares** [comment]
Cexu qui manque doivent ouvrire une issue

**Comment by josephmansour** [comment]
Sujet: Cassandra
https://github.com/josephmansour/cassandra

**Comment by mariobs1990** [comment]
Sujet: Gradle
https://github.com/mariobs1990/Projet-C1-2018

**Comment by etienneeidC1** [comment]
Sujet : Redis DB
https://github.com/etienneeid/CNAM-ProjetC1-2018/blob/master/README.md

**Comment by mouhamad-khalil** [comment]
Sujet: GlassFish
https://mouhamad-khalil.github.io/GlassFish

**Comment by zeinabrachidi** [comment]
https://github.com/zeinabrachidi/Hadoop

**Comment by danielchoubassi** [comment]
Bonjour Dr. Fares,
J'ai crée un nouveau compte github avec l'email @isae.edu.lb
Le nouveau lien vers le repository de la presentation est  : 
https://github.com/danielchoubassi/OAuth/blob/master/README.md
Merci d'avance,
Daniel
